name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Packages
        run: |
          npm install
#      - name: Lint check
#        run: |
#          npm run lint
      - name: run tests
        env:
          NODE_OPTIONS: "--experimental-vm-modules"
        run: |
          npm run test